### ISSUE TITLE
Change of protocol for Unreal Tournament (UT) from gamespy1 to gamespy3

### ISSUE THREAD

**Issue by andersborum** [kurt-stolle/game-server-query#10]
Hi,

it seems that the game Unreal Tournament now uses the v4 version of the gamespy protocol. I believe this change was introduced to Unreal Tournament when the original game servers were taken offline.

I was writing a simple node.js script that polls our server for information and had to change the games.json file from the following:

```
  "ut": {
    "name": "Unreal Tournament",
    "protocol": "gamespy1",
    "options": {
      "port": 7777,
      "port_query_offset": 1
    },
    "params": {}
  }
```
to
```
  "ut": {
    "name": "Unreal Tournament",
    "protocol": "gamespy3",
    "options": {
      "port": 7777,
      "port_query_offset": 1
    },
    "params": {}
  }
```
The latest version of Unreal Tournament uses the v4 version of the gamespy protocol, but apparently it's compatible with v3 (which is supported by game-server-query). I thought it might be quicker to raise the issue (and fix) here, rather than issuing a pull request.

Thanks for providing the game-server-query package.

**Comment by kurt-stolle** [comment]
I have updated the package.
