### ISSUE TITLE
Add Quake Live to games.json

### ISSUE THREAD

**Issue by PredatH0r** [kurt-stolle/game-server-query#6]
Great library!

For Quake Live I had to manually add this to games.json:
  "quakelive": {
    "name": "Quake Live",
    "protocol": "valve",
    "options": { },
    "params": { }
  },

An example server would be 91.233.116.131:27960  (default port)

Quake Live runs game data and browser queries on the same UDP port (multiplexed).
The default server instance uses port 27960, but typically people have more than one server running using additional ports 27961...

**Comment by PredatH0r** [comment]
removed "port_query" from my initial post (caused that the provided port number in the function call was ignored and always returned data for the default server instance)

**Comment by kurt-stolle** [comment]
Hey, please make a Pull Request so that I can apply your patch to the project.
